spring:
  application:
    name: taco-cloud-ch03

  datasource:
    generate-unique-name: false
    name: tacocloud

#spring:
#  application:
#    name: taco-cloud-ch02
#
#  datasource:
#    url: jdbc:h2:mem:tacocloud
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    generate-unique-name: false
#    name: tacocloud
#
#  h2:
#    console:
#      enabled: true
#
#  jdbc:
#    initialize-schema: always
